spring:
  application:
    name: pay-service
  datasource:
    url: jdbc:mysql://mysql8_test:3306/db_operation?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


