server:
  port: 8082

spring:
  application:
    name: historical-service
  kafka:   
    consumer: 
      bootstrap-servers: servicekafka_test:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: historical-events-listener-group
  data: 
    mongodb: 
      uri: mongodb://localhost:27018/db_transaction
      
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}