server:
  port: 8180
  
spring:
  application:
    name: invoces-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_aforo
    username: postgres
    password: jeanjean
    driver-class-name: org.postgresql.Driver
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.ddl-auto: create-drop
    properties:
      hibernate: 
        jdbc:
          lob:
            non_contextual_creation: true
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}            
    
logging:
  level:
    org:
      hibernate.SQL: debug

